services:
  - type: web
    name: my-backend
    env: node
    plan: free
    branch: main            # or the branch you want to deploy
    rootDir: backend        # <-- This tells Render to only use the backend folder
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: your_mongo_atlas_uri
      - key: JWT_SECRET
        value: your_secret_key
      - key: NODE_ENV
        value: production
